version: "3.3"
services:
  mysql:
    image: mariadb:latest
    #restart: always
    deploy:
      restart_policy:
        condition: any
      replicas: 3
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: d9515abe60d1b2aa58a84366
      MYSQL_DATABASE: project
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    networks:
      - mynet

  myredis:
    image: redis:latest
    deploy:
      replicas: 1
    networks:
      - mynet

  myphp:
    image: infs3208_app_myphp
    #build:
    #  context: ./php
    #  dockerfile: dockerfile
    #command: /bin/sh -c "composer update"
    #expose:
    #  - "9000"
    volumes:
      - ./php:/var/www/htdocs
    deploy:
      replicas: 3
    depends_on:
      - mysql
      - myredis
    networks:
      - mynet

  mynginx:
    #build:
    #  context: ./nginx
    #  dockerfile: dockerfile
    image: infs3208_app_mynginx
    volumes:
      #- ./nginx/nginx.ini:/etc/nginx/conf.d/default.conf
      #- ./nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
       - ./php:/var/www/htdocs
    deploy:
      replicas: 3
    ports:
      - "8080:80"
    depends_on:
      - myphp
    networks:
      - mynet

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: php
      PMA_PASSWORD: php
    networks:
      - mynet

  viz:
    image: dockersamples/visualizer
    ports:
      - "9090:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  mynet:
    driver: overlay
