FROM nginx:latest

COPY nginx.conf /etc/nginx/conf.d/
COPY fastcgi-php.conf /etc/nginx/snippets/
COPY php-fpm.conf /etc/nginx/conf.d/
COPY www.conf /etc/nginx/conf.d/

RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y --fix-missing --fix-broken \
    && apt-get install -y nginx
CMD ["nginx", "-g", "daemon off;"]
