FROM php:8.2-fpm

LABEL MAINTAINER="Tayla Ward s4663633@uq.edu.au"


RUN apt-get update \
        && apt-get install -y \
        && docker-php-ext-install mysqli \
        && pecl install redis \
        && docker-php-ext-enable redis \
        && apt-get update && apt-get install -y libicu-dev \
        && docker-php-ext-configure intl \
        && docker-php-ext-install intl \
        && apt-get update \
        && docker-php-ext-install pdo_mysql


RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
        && php composer-setup.php \
        && php -r "unlink('composer-setup.php');" \
        && mv composer.phar /usr/local/bin/composer

WORKDIR /var/www/htdocs

RUN chmod -R 777 /var/www/htdocs

EXPOSE 9000
CMD ["php-fpm"]